### ISSUE TITLE
Change http://localhost:3*** ?

### ISSUE THREAD

**Issue by yusufpeh** [BlockchainWhispers/trailingstoploss3#4]
Hello. Great app. Can we change 3000 to for exp. 3500 ? Because other app localhost same. i cant launch both.

**Comment by csb77** [comment]
You can change that yourself just open the app.js file inside the Application's folder and change line 19:

server.listen(3000);

to this:

server.listen(3500);

**Comment by csb77** [comment]
Let me know if that works for you so I can close this issue.

**Comment by yusufpeh** [comment]
Hello. I tried before this issue and i have "Trailing Stop Loss server is Down!" error.

**Comment by yusufpeh** [comment]
I'm waiting for your help :)

**Comment by csb77** [comment]
You would need to change also in the JS file ... since this wasn't meant to be used across a network, only on your machine. So search for the js file trailing.js and modify the URL for the webservice. 	'http://127.0.0.1:3000/balances/?apiKey=' + $scope.data.userkeys.apikey + "&secretKey=" + $scope.data.userkeys.secretkey

Change 3000 to 3500. Sorry for my late reply, but I am focused mainly on work and this has been a side project I did for fun. Never expected it to be so used to be honest. When I will have some free time I will continue to add some features, like buy back, more exchanges, but at the moment I am currently focused on my job. Hope you will find it useful after you can fix it. 

P.S. I removed the hardcoded URL in the current version on github, but unfortunately I integrated some else's changes without testing too extensively and it broke the tool. I Would still use the version you are having until I take a look and fix it.

**Comment by yusufpeh** [comment]
Ok. It works. Thanks for reply. I will be waiting for updates. (e. g. maybe add bittrex?) Good work. :)
